### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bamartos**

### CODE REVIEW

**Comment by ajoubertza** [comment]
Hi @bamartos.  Could you add a description for this PR, please?  I'm wondering why it was made.  Maybe due a release that is planned?

**Comment by ajoubertza** [comment]
There may also be an issue when trying to install this package, as the `csv2json = dsconfig.callcsv` entry points references a file that no longer exists.  More detail [here](https://github.com/MaxIV-KitsControls/lib-maxiv-dsconfig/pull/12#issuecomment-672755200).

**Comment by HEnquist** [comment]
> There may also be an issue when trying to install this package, as the `csv2json = dsconfig.callcsv` entry points references a file that no longer exists. More detail [here](https://github.com/MaxIV-KitsControls/lib-maxiv-dsconfig/pull/12#issuecomment-672755200).

This is removed now.

**Comment by HEnquist** [comment]
> Hi @bamartos. Could you add a description for this PR, please? I'm wondering why it was made. Maybe due a release that is planned?

The reason for this PR is to move it to python 3.

**Comment by ajoubertza** [comment]
Thanks for updates @HEnquist.

**Pull request merged**
